### ISSUE TITLE
Logo - increase size of Logo

### ISSUE THREAD

**Issue by JazzyBiscuit88** [Summit-DevLabs/SDL-website#50]
![Image](https://github.com/user-attachments/assets/e14878a6-2fe9-478e-a153-c56a38dd5665)

This is really small on desktop. How difficult is it to increase the size?
The name looks top-aligned, rather than center-aligned.

**Comment by jwalls505** [comment]
yea, its all within the viewport settings. I'll mess around and see what I can do.
