### ISSUE TITLE
Logo needs an inverse color

### ISSUE THREAD

**Issue by JazzyBiscuit88** [Summit-DevLabs/SDL-website#77]
When using the hamburger dropdown, the black background makes the logo disappear.

**Comment by JeremiahKW** [comment]
@JazzyBiscuit88 I believe #75 covers this

**Comment by JeremiahKW** [comment]
You should be able to delete this task. #75 has been merged and fixes this issue. Just want to make sure we are on the same page, otherwise I'd do it now.
